---
version: "3"

networks:
  net:

volumes:
  pgsql:

services:
  app:
    image: ghcr.io/fr-bez-aosc/znuny:beta-6.1.1
    container_name: znuny
    environment:
      ZNUNY_TIMEZONE: Europe/Paris
      ZNUNY_DATABASE_HOST: postgresql
      ZNUNY_DATABASE_PORT: 5432
      ZNUNY_DATABASE_NAME: znuny
      ZNUNY_DATABASE_USER: znuny
      ZNUNY_DATABASE_PASSWORD: password
    networks:
      - net
    ports:
      - 8080:80
    depends_on:
      - db
  db:
    image: bitnami/postgresql:16
    container_name: postgresql
    user: root
    environment:
      POSTGRES_DB: znuny
      POSTGRES_USER: znuny
      POSTGRES_PASSWORD: password
      POSTGRESQL_POSTGRES_PASSWORD: password
    volumes:
      - pgsql:/bitnami/postgresql/data
    networks:
      - net
    ports:
      - 5432:5432
  ldap:
    image: bitnami/openldap:2
    container_name: openldap
    networks:
      - net
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: password
      LDAP_ROOT: dc=domain,dc=tld
      LDAP_USERS: znuny,operator
      LDAP_PASSWORDS: password,password