version: "3"

# networks:
#   net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.30.0.0/24

services:
  znuny:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.11
    extends:
      file: compose/znuny.yaml
      service: znuny

  mariadb:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.12
    extends:
      file: compose/mariadb.yaml
      service: mariadb
      
  postgresql:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.13
    extends:
      file: compose/postgresql.yaml
      service: postgresql

  bkp-pgsql:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.13
    extends:
      file: compose/postgresql.yaml
      service: bkp-pgsql
