---
version: "3"

volumes:
  openldap_data:
    driver: local

# networks:
#   net:
#     driver: bridge
#     ipam:
#       config:
#         - subnet: 172.30.0.0/24

services:
  znuny:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.11
    extends:
      file: compose/znuny-dev.yaml
      service: znuny

  mariadb:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.12
    extends:
      file: compose/mariadb.yaml
      service: mariadb

  postgresql:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.13
    extends:
      file: compose/postgresql.yaml
      service: postgresql

  openldap:
    # networks:
    #   net:
    #     ipv4_address: 172.30.0.14
    volumes:
      - openldap_data:/bitnami/openldap
    extends:
      file: compose/openldap.yaml
      service: openldap
