site_name: Documentation
site_url: https://docker-znuny.aosc-portal.com
site_description: Deploy simply and quickly a reliable and performant ticketing application

repo_url: https://github.com/FR-BEZ-AOSC/docker-znuny
repo_name: FR-BEZ-AOSC/docker-znuny

copyright: Copyright &copy; 2023 - 2024 Eviden Open Source Center

extra:
  social:
    - icon: fontawesome/brands/readme
      link: https://doc.znuny.org/znuny_lts
    - icon: fontawesome/brands/github
      link: https://github.com/FR-BEZ-AOSC
    - icon: fontawesome/brands/docker
      link: https://github.com/FR-BEZ-AOSC/docker-znuny/pkgs/container/znuny

nav:
  - Overviews:
    - General: index.md
    - Docker Znuny: overviews/docker-znuny.md
    - Helm Charts: overviews/helm-charts.md
  - Docker Znuny:
    - v6.5.8:
      - Commands: docker-znuny/v6.5.8/commands.md
      - Deployment: docker-znuny/v6.5.8/deployment.md
      - Environment: docker-znuny/v6.5.8/environment.md
      - Features: docker-znuny/v6.5.8/features.md
  - Helm Charts:
    - v0.1.6:
      - Installation: helm-charts/v0.1.6/installation.md
      - Parameters: helm-charts/v0.1.6/parameters.md
      - Usage: helm-charts/v0.1.6/usage.md
      - Upgrade: helm-charts/v0.1.6/upgrade.md
      - Migration: helm-charts/v0.1.6/migration.md
  - Development:
    - Docker Znuny: development/docker-znuny.md
    - Helm Charts: development/helm-charts.md

theme:
  # logo: assets/znuny-logo.jpeg
  name: material
  icon:
    repo: fontawesome/brands/github
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.path
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - toc.follow
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.emoji
  - pymdownx.tasklist
  - pymdownx.arithmatex
  - pymdownx.highlight
  - pymdownx.tabbed

plugins:
  - search
  - git-revision-date-localized
