site_name: Documentation
site_url: https://znuny.aosc-portal.com
site_description: Deploy simply and quickly a reliable and performant ticketing application

repo_url: https://github.com/FR-BEZ-AOSC/docker-znuny
repo_name: FR-BEZ-AOSC/docker-znuny

copyright: Copyright &copy; 2022 - 2023 Eviden Open Source Center

extra:
  version:
    provider: mike
    default: stable
  social:
    - icon: fontawesome/brands/readme
      link: https://doc.znuny.org/znuny_lts
    - icon: fontawesome/brands/github
      link: https://github.com/FR-BEZ-AOSC
    - icon: fontawesome/brands/docker
      link: https://github.com/FR-BEZ-AOSC/docker-znuny/pkgs/container/docker-znuny

nav:
  - Overview: index.md
  - Znuny:
    - Overview: znuny/overview
    - Deployment: znuny/deployment
    - Commands: znuny/commands
    - Development: znuny/development
  - Helm:
    - Overview: helm/overview
    - Deployment: helm/deployment
    - Development: helm/development
  - Roadmaps:
    - v6.5.3-2: roadmaps/v6.5.3-2
    - v6.5.3-3: roadmaps/v6.5.3-3
    - v6.5.3-4: roadmaps/v6.5.3-4
    - v6.5.3-5: roadmaps/v6.5.3-5

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - tables
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.critic
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.inlinehilite
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.betterem
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji 
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight
  - pymdownx.tabbed:
      alternate_style: true
    # anchor_linenums: true
    # line_spans: __span
    # pygments_lang_class: true

theme:
  # logo: assets/znuny-logo.jpeg
  name: material
  icon:
    repo: fontawesome/brands/github
  palette:
    - scheme: default
      primary: orange
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      toggle:
        icon: material/brightness-7 
        name: Switch to light mode
  features:
    - content.code.copy
    - content.tabs.link 
    - navigation.expand
  shortcuts:
    help: 191    # ?
    next: 78     # n
    previous: 80 # p
    search: 83   # s

plugins:
  - mike
  - search
  - git-revision-date-localized
