---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Release.Namespace }}
  labels:
    service: {{ .Release.Name }}
data:
  # Settings: Database
  ZNUNY_DATABASE_TYPE: {{ .Values.config.database.type }}
  ZNUNY_DATABASE_HOST: {{ .Values.config.database.host }}
  ZNUNY_DATABASE_PORT: {{ .Values.config.database.port }}
  ZNUNY_DATABASE_NAME: {{ .Values.config.database.name }}
  ZNUNY_DATABASE_USER: {{ .Values.config.database.user }}
  ZNUNY_DATABASE_PASSWORD: {{ .Values.config.database.password }}
  # Settings: Web server
  ZNUNY_APACHE_REWRITE_RULES: |-
  {{- range .Values.config.webServer.rewriteRules }}
    {{ . }}
  {{- end }}
  # Settings: Users
  ZNUNY_USER_ADMIN_NAME: {{ .Values.config.users.admin.name }}
  ZNUNY_USER_ADMIN_PASSWORD: {{ .Values.config.users.admin.password }}
  # Settings: Mails
  ZNUNY_MAILING_TYPE: {{ .Values.config.mails.type }}
  ZNUNY_MAILING_HOST: {{ .Values.config.mails.host }}
  ZNUNY_MAILING_PORT: {{ .Values.config.mails.port }}
  ZNUNY_MAILING_USER: {{ .Values.config.mails.user }}
  ZNUNY_MAILING_PASSWORD: {{ .Values.config.mails.password }}
  # Settings: Authentications
  {{- range $index, $value := .Values.config.authentications.customers.backends }}
  ZNUNY_CUSTOMER_BACKEND_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $index, $value := .Values.config.authentications.customers.synchronizations }}
  ZNUNY_CUSTOMER_SYNCHRO_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $index, $value := .Values.config.authentications.agents.backends }}
  ZNUNY_AGENTS_BACKEND_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}
  {{- range $index, $value := .Values.config.authentications.agents.synchronizations }}
  ZNUNY_AGENTS_SYNCHRO_{{ add $index 1 }}: |-
    {{- $value | nindent 4 }}
  {{- end }}

