---
version: "3"

volumes:
  mariadb_data:
    driver: local

services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    hostname: mariadb
    # ports:
    #   - 3306:3306
    # volumes:
    #   - mariadb_data:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: password
      MARIADB_DATABASE: znuny
      MARIADB_USER: znuny
      MARIADB_PASSWORD: password
