---
version: "3"

services:
  openldap:
    image: bitnami/openldap:2
    container_name: openldap
    hostname: openldap
    # ports:
    #   - '1389:1389'
    #   - '1636:1636'
    environment:
      LDAP_ADMIN_USERNAME: admin
      LDAP_ADMIN_PASSWORD: password
      LDAP_ROOT: dc=domain,dc=tld
      LDAP_USERS: znuny,operator
      LDAP_PASSWORDS: password,password
