version: "3"

services:
  znuny:
    build:
      context: ..
      dockerfile: ./znuny/Dockerfile
    image: znuny:v6.5.3
    container_name: znuny
    hostname: znuny
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      # Settings: Database
      ZNUNY_DATABASE_TYPE: mysql
      ZNUNY_DATABASE_HOST: mariadb
      ZNUNY_DATABASE_NAME: znuny-db
      ZNUNY_DATABASE_USER: znuny
      ZNUNY_DATABASE_PASSWORD: password
      # Settings: Web server
      ZNUNY_APACHE_REWRITE_RULES: |-
        RewriteRule ^/$ https://%{HTTP_HOST}/otrs/customer.pl
        RewriteRule ^/otrs/$ https://%{HTTP_HOST}/otrs/customer.pl
        RewriteRule ^/otrs$ https://%{HTTP_HOST}/otrs/customer.pl
      # Settings: Application
      ZNUNY_USER_ADMIN_NAME: root@localhost
      ZNUNY_USER_ADMIN_PASSWORD: password
      # Settings: Mails
      ZNUNY_MAILING_TYPE: external
      ZNUNY_MAILING_HOST: smpt.domain.tld
      ZNUNY_MAILING_PORT: 25
      ZNUNY_MAILING_USER: znuny
      ZNUNY_MAILING_PASSWORD: password
      # Settings: Customers
      # ZNUNY_CUSTOMER_BACKEND_1: |-
      # ZNUNY_CUSTOMER_SYNCHRO_1: |-
      # Settings: Agents
      # ZNUNY_AGENT_BACKEND_1: |-
      # ZNUNY_AGENT_SYNCHRO_1: |-
      ZNUNY_TEST_VAR: |
        Ligne 1

        Ligne 3
