---
version: "3"

services:
  znuny:
    build:
      context: ..
      dockerfile: ./znuny/Dockerfile
    image: znuny:v6.5.3
    container_name: znuny
    hostname: znuny
    ports:
      - 8080:80
    depends_on:
      - mariadb
    environment:
      # Settings: Logs
      ZNUNY_LOG_PATH: /var/log/znuny
      # Settings: Database
      ZNUNY_DATABASE_TYPE: mysql
      ZNUNY_DATABASE_HOST: mariadb
      ZNUNY_DATABASE_PORT: 3306
      ZNUNY_DATABASE_NAME: znuny
      ZNUNY_DATABASE_USER: znuny
      ZNUNY_DATABASE_PASSWORD: password
      # Settings: Web server
      ZNUNY_APACHE_DOMAIN: znuny.domain.tld
      ZNUNY_APACHE_REWRITE_RULES: |-
        RewriteRule ^/$ https://%{HTTP_HOST}/otrs/customer.pl
        RewriteRule ^/otrs/$ https://%{HTTP_HOST}/otrs/customer.pl
        RewriteRule ^/otrs$ https://%{HTTP_HOST}/otrs/customer.pl
      # Settings: Users
      ZNUNY_USER_ADMIN_NAME: root@localhost
      ZNUNY_USER_ADMIN_PASSWORD: password
      # Settings: Mails
      ZNUNY_MAILING_TYPE: external
      ZNUNY_MAILING_HOST: smpt.domain.tld
      ZNUNY_MAILING_PORT: 25
      ZNUNY_MAILING_USER: znuny
      ZNUNY_MAILING_PASSWORD: password
      # Settings: Customers
      ZNUNY_CUSTOMER_BACKEND_1: |-
        $$Self->{AuthModule} = 'Kernel::System::Auth::LDAP';
        $$Self->{'AuthModule::LDAP::Host'} = 'ldap.example.com';
        $$Self->{'AuthModule::LDAP::BaseDN'} = 'dc=example,dc=com';
        $$Self->{'AuthModule::LDAP::UID'} = 'uid';
        $$Self->{'AuthModule::LDAP::GroupDN'} = 'cn=znuny-allow,ou=posixGroups,dc=example,dc=com';
        $$Self->{'AuthModule::LDAP::AccessAttr'} = 'memberUid';
        $$Self->{'AuthModule::LDAP::UserAttr'} = 'UID';
        $$Self->{'AuthModule::LDAP::UserAttr'} = 'DN';
      ZNUNY_CUSTOMER_SYNCHRO_1: |-
        $$Self->{'AuthSyncModule'} = 'Kernel::System::Auth::Sync::LDAP';
        $$Self->{'AuthSyncModule::LDAP::Host'} = 'ldap.example.com';
        $$Self->{'AuthSyncModule::LDAP::BaseDN'} = 'dc=example,dc=com';
        $$Self->{'AuthSyncModule::LDAP::UID'} = 'uid';
        $$Self->{'AuthSyncModule::LDAP::SearchUserDN'} = '';
        $$Self->{'AuthSyncModule::LDAP::SearchUserPw'} = '';
        $$Self->{'AuthSyncModule::LDAP::AlwaysFilter'} = '';
        $$Self->{'AuthSyncModule::LDAP::UserSyncMap'} = {
            UserFirstname => 'givenName',
            UserLastname  => 'sn',
            UserEmail     => 'mail',
        };
      # Settings: Agents
      ZNUNY_AGENT_BACKEND_1: |-
        $$Self->{AuthModule} = 'Kernel::System::Auth::LDAP';
        $$Self->{'AuthModule::LDAP::Host'} = 'ldap.example.com';
        $$Self->{'AuthModule::LDAP::BaseDN'} = 'dc=example,dc=com';
        $$Self->{'AuthModule::LDAP::UID'} = 'uid';
        $$Self->{'AuthModule::LDAP::GroupDN'} = 'cn=znuny-allow,ou=posixGroups,dc=example,dc=com';
        $$Self->{'AuthModule::LDAP::AccessAttr'} = 'memberUid';
        $$Self->{'AuthModule::LDAP::UserAttr'} = 'UID';
        $$Self->{'AuthModule::LDAP::UserAttr'} = 'DN';
      ZNUNY_AGENT_SYNCHRO_1: |-
        $$Self->{'AuthSyncModule'} = 'Kernel::System::Auth::Sync::LDAP';
        $$Self->{'AuthSyncModule::LDAP::Host'} = 'ldap.example.com';
        $$Self->{'AuthSyncModule::LDAP::BaseDN'} = 'dc=example,dc=com';
        $$Self->{'AuthSyncModule::LDAP::UID'} = 'uid';
        $$Self->{'AuthSyncModule::LDAP::SearchUserDN'} = '';
        $$Self->{'AuthSyncModule::LDAP::SearchUserPw'} = '';
        $$Self->{'AuthSyncModule::LDAP::AlwaysFilter'} = '';
        $$Self->{'AuthSyncModule::LDAP::UserSyncMap'} = {
            UserFirstname => 'givenName',
            UserLastname  => 'sn',
            UserEmail     => 'mail',
        };
      # Settings: Plugins
      ZNUNY_CUSTOM_PLUGINS:
        - efef
