---
version: "3"

services:
  znuny:
    image: ghcr.io/mln-nicolas-b/docker-znuny:6.5.3-1
    container_name: znuny
    hostname: znuny
    environment:
      ZNUNY_DATABASE_TYPE: mysql
      ZNUNY_DATABASE_HOST: mariadb
      ZNUNY_DATABASE_PORT: 3306
      ZNUNY_DATABASE_NAME: znuny
      ZNUNY_DATABASE_USER: znuny
      ZNUNY_DATABASE_PASSWORD: password

      ZNUNY_APACHE_DOMAIN: znuny.domain.tld
      ZNUNY_APACHE_REWRITE_RULES: |-
        RewriteRule ^/$ https://%{HTTP_HOST}/otrs/customer.pl
        RewriteRule ^/otrs/$ https://%{HTTP_HOST}/otrs/customer.pl
        RewriteRule ^/otrs$ https://%{HTTP_HOST}/otrs/customer.pl

