---
version: "3"

services:
  znuny:
    image: ghcr.io/mln-nicolas-b/docker-znuny:6.5.3-1
    container_name: znuny
    hostname: znuny
    ports:
      - 8080:80
    environment:
      ZNUNY_DATABASE_TYPE: mysql
      ZNUNY_DATABASE_HOST: mariadb
      ZNUNY_DATABASE_PORT: 3306
      ZNUNY_DATABASE_NAME: znuny
      ZNUNY_DATABASE_USER: znuny
      ZNUNY_DATABASE_PASSWORD: password

      ZNUNY_MAILING_TYPE: external
      ZNUNY_MAILING_HOST: smpt.domain.tld
      ZNUNY_MAILING_PORT: 25
      ZNUNY_MAILING_USER: znuny
      ZNUNY_MAILING_PASSWORD: password
