DEFAULT_ZNUNY_DATABASE_HOST="localhost"
DEFAULT_ZNUNY_DATABASE_PORT="5432"
DEFAULT_ZNUNY_DATABASE_NAME="znuny"
DEFAULT_ZNUNY_DATABASE_USER="znuny"
DEFAULT_ZNUNY_DATABASE_PASSWORD="password"

DEFAULT_ZNUNY_APACHE_DOMAIN="_default_"

DEFAULT_ZNUNY_USER_ADMIN_NAME="root@localhost"
DEFAULT_ZNUNY_USER_ADMIN_PASSWORD="password"

DEFAULT_ZNUNY_MAILING_TYPE="sendmail"
