name: Build_Znuny_Containers

on:
  create:
    tags:
      - '*'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Log into ${{ env.REGISTRY }} registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lower case repository name
        run: |
          #bash 4
          echo "IMAGE_NAME_LC=${IMAGE_NAME,,}" >>${GITHUB_ENV}

      - name: Extract previous Docker metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}

      - name: Extract tag name
        id: extract-tag
        run: echo "GIT_TAG=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Build and push Docker image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ env.GIT_TAG }}
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./znuny/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:${{ env.GIT_TAG }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            ${{ github.ref }}

      - name: Build and push Docker image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:latest
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./znuny/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME_LC }}:latest
          labels: |
            ${{ steps.meta.outputs.labels }}
            latest

